### ISSUE TITLE
Multiple key levels?

### ISSUE THREAD

**Issue by cezarsmpio** [srph/react-link-state#1]
For example: 

```
<input type="text" valueLink={linkState(this, 'user[0].login')} />
```

**Comment by srph** [comment]
Something like [react-deep-link-state](https://github.com/EarthlingInteractive/react-deep-link-state) does?

I haven't found a use-case for it. But I'll consider.

Not sure if we should send a PR to the mentioned project, or if I should add the feature here.

**Comment by cezarsmpio** [comment]
Hi @srph, the react-depp-link-state does not support ES6.

I think we need add the feature in this repo.

**Comment by srph** [comment]
Thank for the response :smile:. Yea, that's why I'm thinking of sending a PR so the project would support ES6 :100: . Originally, I only intended to extract out `LinkedStateMixin` and then expose it as a simple function :confused:.

By the way, do you need this ASAP? I can dish it out here if the author of **react-deep-link-state** doesn't consider, if that works for you. :smile:

**Comment by cezarsmpio** [comment]
Yes, I'm on a project and would help me a lot this new feature. I tried, but it was not too long and ended up failing.

You get a new PR today?

Thanks :smile:

**Comment by cezarsmpio** [comment]
Look this: http://blog.sendsonar.com/2015/08/04/angular-like-deep-path-data-bindings-in-react/

**Comment by cezarsmpio** [comment]
And this: https://github.com/tungd/react-catalyst

**Comment by srph** [comment]
OK, I'll work on it probably tonight or tomorrow :100: . I'm still a bit sleepy from work :zzz:

**Comment by srph** [comment]
PR: https://github.com/srph/react-link-state/pull/2

**Comment by srph** [comment]
Released on npm :white_check_mark:
